export * from './header/Header';
export * from './MoviesListCard/MoviesListCard';
export * from './MoviesList/MoviesList';
export * from './userInfo/UserInfo';
export * from './PosterPreview/PosterPreview';
export * from './MovieInfo/MovieInfo';
export * from './GenreBadge/GenreBadge';
export * from './StarsRating/StarsRating';
export * from './Pagination/MyPagination'